
server:
  port : 8080

spring:
  datasource:
    url : jdbc:postgresql://localhost:5432/testLehaim_db
    username : postgres
    password : admin

  jpa:
    generate-ddl : true
    hibernate :
      ddl-auto : validate
    properties:
      hibernate:
        dialect : org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    enabled: true


  output:
    ansi:
      enabled : always

command-line-runner:
  data-loading:
    catalog:
      enabled : false
    patients:
      enabled : true
    recommendations:
      enabled : false


logging:
  level:
    root: INFO
    ru.vaganov.ResourceServer.services: DEBUG
    ru.vaganov.ResourceServer.controllers: DEBUG

springdoc:
  show-actuator: false
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
