
server:
  port : 8080

spring:
  datasource:
    url : jdbc:postgresql://localhost:5432/OncologicalTestsDB
    username : postgres
    password : admin


  jpa:
    generate-ddl : true
    hibernate :
      ddl-auto : create
    properties:
      hibernate:
        dialect : org.hibernate.dialect.PostgreSQLDialect


command-line-runner:
  data-loading:
    catalog:
      enabled : false
    patients:
      enabled : true




springdoc:
  show-actuator: false
  swagger-ui:
    enabled: true
    path: /swagger-ui.html