
server:
  port : 8080

spring:
  datasource:
    url : jdbc:postgresql://localhost:5432/OncologicalTestsDB
    username : postgres
    password : admin


  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    cache: false


  jpa:
    generate-ddl : true
    hibernate :
      ddl-auto : update
    properties:
      hibernate:
        dialect : org.hibernate.dialect.PostgreSQLDialect


  output:
    ansi:
      enabled : always


command-line-runner:
  data-loading:
    catalog:
      enabled : true
    patients:
      enabled : true
    recommendations:
      enabled : false


logging:
  level:
    root: INFO
    ru.vaganov.ResourceServer.services: DEBUG
    ru.vaganov.ResourceServer.controllers: DEBUG

springdoc:
  show-actuator: false
  swagger-ui:
    enabled: true
    path: /swagger-ui.html