
server:
  port=8080:

spring:
  datasource:
    url : jdbc:postgresql://localhost:5432/OncologicalTestsDB
    username : postgres
    password : admin
  jpa:
    generate-ddl : true
    properties:
      hibernate:
        dialect : org.hibernate.dialect.PostgreSQLDialect
        ddl-auto : update